language: node_js
node_js:
- "stable"

cache:
  directories:
    - 'node_modules'

services:
  - postgresql
  
before_script:
  - npm run createdb
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - npm run build

script:
  - npm run test
after_success:
  - npm run coverage

